# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Bulgarian Utility Outage Checker"
  org.opencontainers.image.description: "Проверка за аварии на комунални услуги в България / Check for planned and unplanned utility outages in Bulgaria"
  org.opencontainers.image.source: "https://github.com/reminchev/bulgarian_utility_outage_checker"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
